import os

POSTGRES_DATABASE_USERNAME = os.getenv("POSTGRES_DATABASE_USERNAME")
POSTGRES_DATABASE_PASSWORD = os.getenv("POSTGRES_DATABASE_PASSWORD")
POSTGRES_DATABASE_URL = os.getenv("POSTGRES_DATABASE_URL")
POSTGRES_DATABASE_PORT = os.getenv("POSTGRES_DATABASE_PORT")
POSTGRES_DATABASE_NAME = os.getenv("POSTGRES_DATABASE_NAME")
POSTGRES_DATABASE_URI = f'postgresql://{POSTGRES_DATABASE_USERNAME}:{POSTGRES_DATABASE_PASSWORD}@{POSTGRES_DATABASE_URL}:{POSTGRES_DATABASE_PORT}/{POSTGRES_DATABASE_NAME}'

if not POSTGRES_DATABASE_USERNAME and not POSTGRES_DATABASE_PASSWORD and not POSTGRES_DATABASE_URL and not POSTGRES_DATABASE_PORT and not POSTGRES_DATABASE_NAME:
    POSTGRES_DATABASE_URI = 'postgresql://admin:mysecretpassword@localhost:5432/postgres'
